kconfig: disable BLK_DEV_INITRD
Needed to support CoreUtils' 'date' and avoid:

  ERROR: Timestamp out of range for cpio format

That's because 'date -d0 +%s' returns a negative value with the
CoreUtils version.

Signed-off-by: Matthieu Baerts (NGI0) <matttbe@kernel.org>