docker: add python3-setuptools for Perf
Perf now needs it, see

  commit ee87a0841aa5 ("perf python: Avoid deprecation warning on distutils")

To avoid:

  ModuleNotFoundError: No module named 'setuptools'

Signed-off-by: Matthieu Baerts <matthieu.baerts@tessares.net>